Repository aalamu/detective-z, pull requests merged in 2025-01, with the labels that each got.

#2 Implement Investigation Module with OpenAI Integration and Exception Handling
  .gitattributes
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/fleencorp/detectivez/DetectiveZApplication.java
  src/main/java/com/fleencorp/detectivez/adapter/InvestigationAdapter.java
  src/main/java/com/fleencorp/detectivez/adapter/impl/ExternalInvestigationAdapter.java
  src/main/java/com/fleencorp/detectivez/controller/InvestigationController.java
  src/main/java/com/fleencorp/detectivez/exception/GlobalExceptionHandler.java
  src/main/java/com/fleencorp/detectivez/model/dto/InvestigateDto.java
  src/main/java/com/fleencorp/detectivez/model/request/InvestigateRequest.java
  src/main/java/com/fleencorp/detectivez/model/response/InvestigateResponse.java
  src/main/java/com/fleencorp/detectivez/model/response/external/ExternalInvestigateResponse.java
  src/main/java/com/fleencorp/detectivez/service/InvestigationService.java
  src/main/java/com/fleencorp/detectivez/service/impl/InvestigationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/investigate.html
Labels: bug, documentation, enhancement, help wanted

#4 Update App Server Port
  src/main/resources/application.properties
Labels: enhancement

#8 Add Validation Message and Update Link Field Constraints
  src/main/java/com/fleencorp/detectivez/model/dto/InvestigateDto.java
  src/main/resources/ValidationMessage.properties
Labels: enhancement, good first issue

#10 Renamed ValidationMessage.properties
  src/main/resources/ValidationMessages.properties
Labels: bug
